/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import dao.Produto;
import dao.Tipologia;
import dao.TipologiaDAO;
import dao.VariaveisDAO;
import guiAntesInclusoes.JTableAntesIncluirTipologia;
import guiIncluirAlterar.JTableIncluirAlterarTipologia;
import sistema.MySQLDumper;

/**
 *
 * @author luisf
 */

@SuppressWarnings("serial")
public class TelaTipologias extends javax.swing.JFrame implements KeyListener{
	
	Produto ProdutoAberto;

    /**
     * Creates new form TelaOrcamentosNew
     */
    public TelaTipologias(Produto produto) {
    	
    	
    	    addKeyListener(this);
 	        setFocusable(true);
            setFocusTraversalKeysEnabled(false);
            
    		ProdutoAberto = produto;
    	
        	initComponents(produto);

            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            jTable2.setRowSorter(new TableRowSorter<DefaultTableModel>(modelo));
                      
            readJTable(produto);
    }
    
    public TelaTipologias() {
    	
    	addKeyListener(this);
	        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
        
    }

    
    

  public void readJTable(Produto produto) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        jTable2.setRowSorter(new TableRowSorter<DefaultTableModel>(modelo));

        modelo.setNumRows(0);
        TipologiaDAO tdao = new TipologiaDAO();
        
        	for (Tipologia t : tdao.lerParaProduto(produto)) {
        		modelo.addRow(new Object[]{  
                t.getIdTipologia(),		
                t.getCodigo_componente(),
                t.getDescricaoComponente(),
                t.getMultiplicadorAltura(),
                t.getOffsetAltura(),
                t.getMultiplicadorLargura(),
                t.getOffsetLargura(),
                t.getPeso_por_metro()
        		});
        	}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Produto produto) {

    	
    	setTitle("Sistema para cálculo de esquadrias -> Produtos -> Tipologia");

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));

        jButton7.setText("Voltar (produtos)");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição"));

        jButton1.setText("INCLUIR COMPONENTE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setToolTipText("Inclui um componente na tipologia do produto");

        jButton2.setText("EXCLUIR COMPONENTE");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setToolTipText("Exclui o componente selecionado da tipologia do produto");

        jButton3.setText("ALTERAR COMPONENTE");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setToolTipText("Altera os multiplicadores e offsets do componente selecionado");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "id_tipologia", "codigo_componente", "descricao", "multiplicadoraltura", "offsetaltura", "multiplicadorlargura", "offsetlargura", "peso_por_metro"}
            ) { boolean[] podeEditar = new boolean [] {false, false, false, false, false, false, false,false};
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return podeEditar [columnIndex];
                }
        });
        
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt2) {
            	jTable2MouseClicked(evt2);
            }
        });
        
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        
        jScrollPane2.setViewportView(jTable2);

        scrollPane2.add(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editando tipologia do produto nº "+produto.getIdProduto()+" - "+produto.getDescricao());
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER); 
       

        jMenu3.setText("Backup");

        jMenuItem1.setText("Exportar BD");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Importar BD");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Valores Globais");

        jMenuItem3.setText("Valor do quilo do alumínio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem5.setText("Valor do quilo do contramarco");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);
        
        jMenuItem4.setText("Mão de obra (%)");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               ))
                        .addGap(0, 0, Short.MAX_VALUE))
                    )
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    )
                .addGap(5, 5, 5)
                
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    	this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }// </editor-fold>                        

    int selecao = -1;
    int linhaSelecionada = -1;
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {                                     
    	
    	if (selecao != -1) {
    		if (selecao == 0 && linhaSelecionada == jTable2.getSelectedRow()) {
    			selecao = jTable2.getSelectedRow();
    	  
    	
    			if(jTable2.getSelectedRow() != -1) {
    		    	TipologiaDAO tdao = new TipologiaDAO();
    		    	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
    		    	
    		    	this.dispose();
    		    	new JTableIncluirAlterarTipologia(t).setVisible(true);
    		    	} else {JOptionPane.showMessageDialog(null, "Selecione um componente da tipologia para alterar!");}
    		
    			selecao = -1;
    		linhaSelecionada = -1;
    		} else { selecao = -1; linhaSelecionada = -1;}
    	} else {selecao = 0; linhaSelecionada = jTable2.getSelectedRow();}
    }   
    
    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {
    	
    	int key = evt.getKeyCode();
    	
    	if(key == KeyEvent.VK_ENTER)
         {
             
    		if(jTable2.getSelectedRow() != -1) {
    	    	TipologiaDAO tdao = new TipologiaDAO();
    	    	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
    	    	
    	    	this.dispose();
    	    	new JTableIncluirAlterarTipologia(t).setVisible(true);
    	    	} else {JOptionPane.showMessageDialog(null, "Selecione um componente da tipologia para alterar!");}
    		
         } else if(key == KeyEvent.VK_DELETE)
         {
             
        	 
        	 	if(jTable2.getSelectedRow() != -1) {
        	        
               		if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o componente\n da tipologia deste produto?")==0) {
               		TipologiaDAO tdao = new TipologiaDAO();
                	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
                	
                	tdao.delete(t);
                	
                	readJTable(ProdutoAberto);
          
               		}
                	} else {JOptionPane.showMessageDialog(null, "Selecione uma componente da tipologia para excluir!");}
    		 
         }
    }

    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        MySQLDumper.export();
    }                                          

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	this.dispose();
    	new TelaProdutos().setVisible(true);
    }                                        

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        JOptionPane.showMessageDialog(null, "Função ainda não implementada, caso precise recuperar o backup fale com o desenvolvedor do sistema!");

    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	VariaveisDAO vdao = new VariaveisDAO();
        if(!vdao.procurarReferencia()){
            vdao.criarReferencia();
        }
        double valorAluminio = vdao.lerVariavel("precoaluminio");
        
        String novoValor =  JOptionPane.showInputDialog("O preço atual do aluminio é: R$"+valorAluminio+"\n"
                + "Digite um novo valor para atualizar ou cancele para manter o valor atual");
        if(!novoValor.isEmpty()){
            double novoValor2 = Double.parseDouble(novoValor);
            vdao.update("precoaluminio", novoValor2);
        }
        vdao.atualizarVariavelLocal();
    }                                          

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	   VariaveisDAO vdao = new VariaveisDAO();
           if(!vdao.procurarReferencia()){
               vdao.criarReferencia();
           }
           double porcentagemMDO = vdao.lerVariavel("porcentagemmdo");
           
           String novoValor =  JOptionPane.showInputDialog("A porcentagem atual da mao de obra é: "+porcentagemMDO+"%\n"
                   + "Digite um novo valor para atualizar ou cancele para manter o valor atual");
           if(!novoValor.isEmpty()){
               double novoValor2 = Integer.parseInt(novoValor);
               vdao.update("porcentagemmdo", novoValor2);
           }
           vdao.atualizarVariavelLocal();
    }                        
    
  private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        VariaveisDAO vdao = new VariaveisDAO();
        if(!vdao.procurarReferencia()){
            vdao.criarReferencia();
        }
        double valorContramarco = vdao.lerVariavel("precocontramarco");
        
        String novoValor =  JOptionPane.showInputDialog("O preço atual do contramarco é: R$"+valorContramarco+"\n"
                + "Digite um novo valor para atualizar ou cancele para manter o valor atual");
        if(!novoValor.isEmpty()){
            double novoValor2 = Integer.parseInt(novoValor);
            vdao.update("precocontramarco", novoValor2);
        }
        vdao.atualizarVariavelLocal();

    }   
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	
    	this.dispose();
    	new JTableAntesIncluirTipologia(ProdutoAberto).setVisible(true);
    	
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

       	if(jTable2.getSelectedRow() != -1) {
        
       		if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o componente\n da tipologia deste produto?")==0) {
       		TipologiaDAO tdao = new TipologiaDAO();
        	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
        	
        	tdao.delete(t);
        	
        	readJTable(ProdutoAberto);
  
       		}
        	} else {JOptionPane.showMessageDialog(null, "Selecione uma componente da tipologia para excluir!");}
        	
       	
        }                                                            

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	
    	if(jTable2.getSelectedRow() != -1) {
    	TipologiaDAO tdao = new TipologiaDAO();
    	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
    	
    	this.dispose();
    	new JTableIncluirAlterarTipologia(t).setVisible(true);
    	} else {JOptionPane.showMessageDialog(null, "Selecione um componente da tipologia para alterar!");}
    	
    }                  
    
    @Override
    public void keyTyped(KeyEvent e) {
    	
    	
    }

    @Override
    public void keyPressed(KeyEvent e) {
    	 
    	int key = e.getKeyCode();
    	
    	if(key == KeyEvent.VK_ENTER)
         {
             
    		if(jTable2.getSelectedRow() != -1) {
    	    	TipologiaDAO tdao = new TipologiaDAO();
    	    	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
    	    	
    	    	this.dispose();
    	    	new JTableIncluirAlterarTipologia(t).setVisible(true);
    	    	} else {JOptionPane.showMessageDialog(null, "Selecione um componente da tipologia para alterar!");}
    		
         } else if(key == KeyEvent.VK_DELETE)
         {
             
        	 
        	 	if(jTable2.getSelectedRow() != -1) {
        	        
               		if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o componente\n da tipologia deste produto?")==0) {
               		TipologiaDAO tdao = new TipologiaDAO();
                	Tipologia t = tdao.lerObjTipologia(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
                	
                	tdao.delete(t);
                	
                	readJTable(ProdutoAberto);
          
               		}
                	} else {JOptionPane.showMessageDialog(null, "Selecione uma componente da tipologia para excluir!");}
    		 
         }
    	 
    	 
    	
    }

    @Override
    public void keyReleased(KeyEvent e) {
    	// TODO Auto-generated method stub
    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTipologias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTipologias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTipologias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTipologias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTipologias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.awt.ScrollPane scrollPane2;
    // End of variables declaration                   
}
