package guiAntesInclusoes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import gui.TelaComponentes;
import guiIncluirAlterar.JTableIncluirAlterarComponente;
import sistema.Conexao;

/**
*
* @author luisf
*/
@SuppressWarnings("serial")
public class JTableAntesIncluirComponente extends javax.swing.JFrame implements KeyListener{

   /**
    * Creates new form JTableAntesIncluirComponente
    */
   public JTableAntesIncluirComponente() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jButton1 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jTextField1 = new javax.swing.JTextField();
       jLabel1 = new javax.swing.JLabel();

       setResizable(false);
       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jButton1.setText("OK");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       jButton2.setText("Cancelar");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });
       
       jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
           public void keyPressed(java.awt.event.KeyEvent evt) {
               jTextField1KeyPressed(evt);
           }
       });

       jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
       jLabel1.setText("Digite o código do novo componente:");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jTextField1)
               .addContainerGap())
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
               .addContainerGap())
           .addGroup(layout.createSequentialGroup()
               .addGap(35, 35, 35)
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(34, 34, 34))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(18, 18, 18)
               .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton1)
                   .addComponent(jButton2))
               .addContainerGap())
       );

       jTextField1.requestFocus(true);
       
       pack();
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

   }// </editor-fold>                        

   private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {                                     
	   if(evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
		   String novoCodigoComponente = new String();
			
			novoCodigoComponente = jTextField1.getText().toString();
       	
       		if(!novoCodigoComponente.contentEquals("")) {
           
       			try {
       				
       				Connection conexao = Conexao.getConnection();

	        			PreparedStatement	stmt = conexao.prepareStatement("SELECT codigo_componente FROM prisma.componente WHERE codigo_componente LIKE ?;");
	        			stmt.setString(1, novoCodigoComponente);
	
	        			ResultSet rs = stmt.executeQuery();
				
	        			if(rs.next()) {
	        				
	        				JOptionPane.showMessageDialog(null, "Código ja existente no banco de dados, digite um código diferente ou caso deseje alterar "
	        						+ "o componente '"+novoCodigoComponente+"' o selecione na tela 'Componentes' e clique em ALTERAR ou EXCLUIR!");
	        				
	        				jTextField1.setText("");
	        				
	        			} else {
	        				
	        					this.dispose();
	        					new JTableIncluirAlterarComponente(novoCodigoComponente).setVisible(true);;
	    	
	        			}
		
       			} catch(SQLException e) {JOptionPane.showMessageDialog(null, "Erro ao verificar se o componente digitado ja existe no Banco de dados!");}
       		} else {

       				JOptionPane.showMessageDialog(null, "Digite um código para o novo componente!");
	
       		}
       } else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
       	{
    	   this.dispose();
    	   new TelaComponentes().setVisible(true);
       	}
	   
   }   

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

	   this.dispose();
	   new TelaComponentes().setVisible(true);
	   
   }                                        

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
	    String novoCodigoComponente = new String();
		
			novoCodigoComponente = jTextField1.getText().toString();
        	
        		if(!novoCodigoComponente.contentEquals("")) {
            
        			try {
        				
        				Connection conexao = Conexao.getConnection();

	        			PreparedStatement	stmt = conexao.prepareStatement("SELECT codigo_componente FROM prisma.componente WHERE codigo_componente LIKE ?;");
	        			stmt.setString(1, novoCodigoComponente);
	
	        			ResultSet rs = stmt.executeQuery();
				
	        			if(rs.next()) {
	        				
	        				JOptionPane.showMessageDialog(null, "Código ja existente no banco de dados, digite um código diferente ou caso deseje alterar "
	        						+ "o componente '"+novoCodigoComponente+"' o selecione na tela 'Componentes' e clique em ALTERAR ou EXCLUIR!");
	        				
	        				jTextField1.setText("");
	        				
	        			} else {
	        				
	        					this.dispose();
	        					new JTableIncluirAlterarComponente(novoCodigoComponente).setVisible(true);;
	    	
	        			}
		
        			} catch(SQLException e) {JOptionPane.showMessageDialog(null, "Erro ao verificar se o componente digitado ja existe no Banco de dados!");}
        		} else {

        				JOptionPane.showMessageDialog(null, "Digite um código para o novo componente!");
	
        		}
 	   	   
   }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(JTableAntesIncluirComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(JTableAntesIncluirComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(JTableAntesIncluirComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(JTableAntesIncluirComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new JTableAntesIncluirComponente().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration   
   
   @Override
   public void keyTyped(KeyEvent e) {
   	
   	
   }

   @Override
   public void keyPressed(KeyEvent evt) {
   	 
   	int key = evt.getKeyCode();
   	
   	if(key == KeyEvent.VK_ENTER)
        {
            
   	 String novoCodigoComponente = new String();
		
		novoCodigoComponente = jTextField1.getText().toString();
 	
 		if(!novoCodigoComponente.contentEquals("")) {
     
 			try {
 				
 				Connection conexao = Conexao.getConnection();

     			PreparedStatement	stmt = conexao.prepareStatement("SELECT codigo_componente FROM prisma.componente WHERE codigo_componente LIKE ?;");
     			stmt.setString(1, novoCodigoComponente);

     			ResultSet rs = stmt.executeQuery();
			
     			if(rs.next()) {
     				
     				JOptionPane.showMessageDialog(null, "Código ja existente no banco de dados, digite um código diferente ou caso deseje alterar "
     						+ "o componente '"+novoCodigoComponente+"' o selecione na tela 'Componentes' e clique em ALTERAR ou EXCLUIR!");
     				
     				jTextField1.setText("");
     				
     			} else {
     				
     					this.dispose();
     					new JTableIncluirAlterarComponente(novoCodigoComponente).setVisible(true);;
 	
     			}
	
 			} catch(SQLException e) {JOptionPane.showMessageDialog(null, "Erro ao verificar se o componente digitado ja existe no Banco de dados!");}
 		} else {

 				JOptionPane.showMessageDialog(null, "Digite um código para o novo componente!");

 		}
   			
        } else if(key == KeyEvent.VK_ESCAPE)
        {
            
       	 

     	   this.dispose();
     	   new TelaComponentes().setVisible(true);
     	   
   		 
        }
   	 
   	 
   	
   }

   @Override
   public void keyReleased(KeyEvent e) {
   	// TODO Auto-generated method stub
   	
   }
   
}
