package guiIncluirAlterar;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JOptionPane;

import dao.ItemOrcamento;
import dao.ItemOrcamentoDAO;
import dao.Orcamento;
import dao.OrcamentoDAO;
import dao.Produto;
import gui.TelaItensOrcamento;

/**
*
* @author luisf
*/
@SuppressWarnings("serial")
public class JTableIncluirAlterarItemOrcamento extends javax.swing.JFrame {
	
	int idItemOrcamento = -1;
    ItemOrcamentoDAO itemOrcamentoDAO = new ItemOrcamentoDAO();
    Orcamento orcamentoAberto = new Orcamento(false);
    Produto produtoAberto = new Produto();

   /**
    * Creates new form JTableIncluirCliente
    */
//   public JTableIncluirAlterarItemOrcamento() {
//       initComponents();
//   }
   
   public JTableIncluirAlterarItemOrcamento(ItemOrcamento itemOrcamento) {
       initComponents(itemOrcamento);
   }
   
   public JTableIncluirAlterarItemOrcamento(Orcamento orcamento,Produto produto) {
	   
	   orcamentoAberto = orcamento;
	   produtoAberto = produto;
       initComponents(orcamento,produto);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//   private void initComponents() {
//
//	   setTitle("Sistema para cálculo de esquadrias -> Orçamentos -> Itens orçamento -> Incluir produto");
//
//       buttonGroup1 = new javax.swing.ButtonGroup();
//       buttonGroup2 = new javax.swing.ButtonGroup();
//       jPanel1 = new javax.swing.JPanel();
//       jLabel1 = new javax.swing.JLabel();
//       jLabel2 = new javax.swing.JLabel();
//       jLabel3 = new javax.swing.JLabel();
//       jLabel4 = new javax.swing.JLabel();
//       jLabel5 = new javax.swing.JLabel();
//       jLabel6 = new javax.swing.JLabel();
//       jLabel7 = new javax.swing.JLabel();
//       jLabel8 = new javax.swing.JLabel();
//       txtAltura = new javax.swing.JTextField();
//       txtLargura = new javax.swing.JTextField();
//       txtQuantidade = new javax.swing.JTextField();
//       jButton1 = new javax.swing.JButton();
//       jButton2 = new javax.swing.JButton();
//       jLabel11 = new javax.swing.JLabel();
//       jPanel2 = new javax.swing.JPanel();
//       jRadioButton1 = new javax.swing.JRadioButton();
//       jRadioButton2 = new javax.swing.JRadioButton();
//       jComboBox1 = new javax.swing.JComboBox<>();
//       jPanel4 = new javax.swing.JPanel();
//       jComboBox2 = new javax.swing.JComboBox<>();
//       jComboBox3 = new javax.swing.JComboBox<>();
//       jComboBox4 = new javax.swing.JComboBox<>();
//       jRadioButton3 = new javax.swing.JRadioButton();
//       jRadioButton4 = new javax.swing.JRadioButton();
//       labelCabecalho = new javax.swing.JLabel();
//
//       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//       jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));
//
//       jLabel2.setText("*Altura (mm):");
//
//       jLabel3.setText("*Largura (mm):");
//
//       jLabel5.setText("*Quantidade:");
//
//       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//       jPanel1.setLayout(jPanel1Layout);
//       jPanel1Layout.setHorizontalGroup(
//           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(jPanel1Layout.createSequentialGroup()
//               .addContainerGap()
//               .addComponent(jLabel2)
//               .addGap(18, 18, 18)
//               .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//               .addComponent(jLabel3)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//               .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//               .addComponent(jLabel5)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//               .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//       );
//       jPanel1Layout.setVerticalGroup(
//           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(jPanel1Layout.createSequentialGroup()
//               .addContainerGap()
//               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                   .addComponent(jLabel2)
//                   .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(jLabel3)
//                   .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(jLabel5)
//                   .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//       );
//
//
//       jButton1.setText("INCLUIR");
//       jButton1.addActionListener(new java.awt.event.ActionListener() {
//           public void actionPerformed(java.awt.event.ActionEvent evt) {
//               jButton1ActionPerformed(evt);
//           }
//       });
//
//       jButton2.setText("CANCELAR");
//       jButton2.addActionListener(new java.awt.event.ActionListener() {
//           public void actionPerformed(java.awt.event.ActionEvent evt) {
//               jButton2ActionPerformed(evt);
//           }
//       });
//
//       jLabel11.setText("Os campos com * são obrigatórios.");
//
//       jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contramarco"));
//
//       buttonGroup1.add(jRadioButton1);
//       jRadioButton1.setText("Sem contramarco");
//
//       buttonGroup1.add(jRadioButton2);
//       jRadioButton2.setText("Com contramarco");
//
//       ItemOrcamentoDAO comboBoxDAO = new ItemOrcamentoDAO();
//       
//       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxDAO.carregarComboxContramarco()));
//       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxDAO.carregarComboxArremate()));
//       jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxDAO.carregarComboxContramarco()));
//       jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxDAO.carregarComboxArremate()));
//
//       
//       
//
//       jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//       jLabel4.setText("Laterais + Superior");
//
//
//       jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//       jLabel6.setText("Inferior");
//       
//       jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//       jLabel7.setText("Laterais + Superior");
//
//       jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//       jLabel8.setText("Inferior");
//
//       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//       jPanel2.setLayout(jPanel2Layout);
//       jPanel2Layout.setHorizontalGroup(
//           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(jPanel2Layout.createSequentialGroup()
//               .addContainerGap()
//               .addComponent(jRadioButton1)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//               .addComponent(jRadioButton2)
//               .addGap(18, 18, 18)
//               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                   .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
//                   .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//               .addGap(18, 18, Short.MAX_VALUE)
//               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                   .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                   .addComponent(jComboBox3, 0, 120, Short.MAX_VALUE))
//               .addGap(18, 18, 18))
//       );
//       jPanel2Layout.setVerticalGroup(
//           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(jPanel2Layout.createSequentialGroup()
//               .addContainerGap()
//               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                   .addComponent(jLabel4)
//                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                   .addComponent(jRadioButton1)
//                   .addComponent(jRadioButton2)
//                   .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//       );
//       
//       jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Arremate"));
//
//       buttonGroup2.add(jRadioButton3);
//       jRadioButton3.setText("Sem arremate");
//       jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
//           public void actionPerformed(java.awt.event.ActionEvent evt) {
//               jRadioButton3ActionPerformed(evt);
//           }
//       });
//
//       buttonGroup2.add(jRadioButton4);
//       jRadioButton4.setText("Com arremate");
//
//       javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//       jPanel4.setLayout(jPanel4Layout);
//       jPanel4Layout.setHorizontalGroup(
//           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(jPanel4Layout.createSequentialGroup()
//               .addContainerGap()
//               .addComponent(jRadioButton3)
//               .addGap(18, 18, 18)
//               .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                   .addGroup(jPanel4Layout.createSequentialGroup()
//                       .addGap(20, 20, 20)
//                       .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
//                   .addGroup(jPanel4Layout.createSequentialGroup()
//                       .addGap(18, 18, 18)
//                       .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
//               .addGap(16, 16, 16)
//               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                   .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
//               .addContainerGap(18, Short.MAX_VALUE))
//       );
//       jPanel4Layout.setVerticalGroup(
//           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(jPanel4Layout.createSequentialGroup()
//               .addContainerGap()
//               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                   .addComponent(jLabel7)
//                   .addComponent(jLabel8))
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                   .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(jRadioButton3)
//                   .addComponent(jRadioButton4)
//                   .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
//               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//       );
//
//       labelCabecalho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
//       //labelCabecalho.setText("jLabel4");
//
//       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//       getContentPane().setLayout(layout);
//       layout.setHorizontalGroup(
//           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(layout.createSequentialGroup()
//               .addGap(34, 34, 34)
//               .addComponent(jButton1)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//               .addComponent(jButton2)
//               .addGap(35, 35, 35))
//           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
//           .addGroup(layout.createSequentialGroup()
//               .addContainerGap()
//               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                   .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                   .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(labelCabecalho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
//                   .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                   .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//       );
//       layout.setVerticalGroup(
//           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//           .addGroup(layout.createSequentialGroup()
//               .addGap(0, 0, 0)
//               .addComponent(jLabel1)
//               .addGap(18, 18, 18)
//               .addComponent(labelCabecalho)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//               .addComponent(jLabel11)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//               .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                   .addComponent(jButton1)
//                   .addComponent(jButton2))
//               .addContainerGap())
//       );
//
//       pack();
//       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//   	   this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
//   }// </editor-fold>  
    
   
   //tela alterar
   private void initComponents(ItemOrcamento itemOrcamento) {

	   idItemOrcamento = itemOrcamento.getIdItensOrcamento();
	   
	   setTitle("Sistema para cálculo de esquadrias -> Orçamentos -> Itens orçamento -> Alterar produto");
       buttonGroup1 = new javax.swing.ButtonGroup();
       buttonGroup2 = new javax.swing.ButtonGroup();
       jPanel1 = new javax.swing.JPanel();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       jLabel5 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel7 = new javax.swing.JLabel();
       jLabel8 = new javax.swing.JLabel();

       txtAltura = new javax.swing.JTextField();
       txtLargura = new javax.swing.JTextField();
       txtQuantidade = new javax.swing.JTextField();
       jLabel1 = new javax.swing.JLabel();
       jButton3 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jLabel11 = new javax.swing.JLabel();
       jPanel2 = new javax.swing.JPanel();
       jRadioButton1 = new javax.swing.JRadioButton();
       jRadioButton2 = new javax.swing.JRadioButton();
       jComboBox1 = new javax.swing.JComboBox<>();
       jPanel4 = new javax.swing.JPanel();
       jComboBox2 = new javax.swing.JComboBox<>();
       jComboBox3 = new javax.swing.JComboBox<>();
       jComboBox4 = new javax.swing.JComboBox<>();

       jRadioButton3 = new javax.swing.JRadioButton();
       jRadioButton4 = new javax.swing.JRadioButton();
       labelCabecalho = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));

       jLabel2.setText("*Altura (mm):");

       jLabel3.setText("*Largura (mm):");

       jLabel5.setText("*Quantidade:");

       jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel4.setText("Laterais + Superior");

       jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel6.setText("Inferior");
       
       jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel7.setText("Laterais + Superior");

       jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel8.setText("Inferior");
       
       labelCabecalho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
       labelCabecalho.setText("Alterando o produto nº "+itemOrcamento.getIdProduto()+" do orçamento nº "+itemOrcamento.getIdOrcamento()+".");

       jLabel11.setText("Os campos com * são obrigatórios.");
       
       txtAltura.setText(""+itemOrcamento.getAlturaMm());
       txtLargura.setText(""+itemOrcamento.getLarguraMm());
       txtQuantidade.setText(""+itemOrcamento.getQuantidade());
               
       buttonGroup1.add(jRadioButton1);
       jRadioButton1.setText("Sem contramarco");
       jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton1ActionPerformed(evt);
           }
       });
       
       buttonGroup1.add(jRadioButton2);
       jRadioButton2.setText("Com contramarco");
       jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton2ActionPerformed(evt);
           }
       });
       
       buttonGroup2.add(jRadioButton3);
       jRadioButton3.setText("Sem arremate");
       jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton3ActionPerformed(evt);
           }
       });

       buttonGroup2.add(jRadioButton4);
       jRadioButton4.setText("Com arremate");
       jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton4ActionPerformed(evt);
           }
       });
       
       
       //Configurar os radiobuttons e combobox
       
       if(itemOrcamento.getContramarco().toString().contentEquals("Não") && 
          itemOrcamento.getContramarcoInferior().toString().contentEquals("Não") ) {
    	   
           jRadioButton1.setSelected(true);
           
           jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
           jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
           
           jComboBox1.setEnabled(false);
           jComboBox3.setEnabled(false);
           
           } else {
        	   
        	   jRadioButton2.setSelected(true);
        	   
    	       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxContramarco()));
    	       jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxContramarco()));

        	   jComboBox1.setSelectedItem(itemOrcamento.getContramarco().toString());
        	   jComboBox3.setSelectedItem(itemOrcamento.getContramarcoInferior().toString());

           
           }
       
       
       
       if(itemOrcamento.getArremate().toString().contentEquals("Não") &&
          itemOrcamento.getArremateInferior().toString().contentEquals("Não")) {
    	   
           jRadioButton3.setSelected(true);
           
           jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
           jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));

           
           jComboBox2.setEnabled(false);
           jComboBox4.setEnabled(false);
           
           } else {
        	   
        	   jRadioButton4.setSelected(true);
        	   
      	       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxArremate()));
      	       jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxArremate()));

      	       
      	       
    	   	   jComboBox2.setSelectedItem(itemOrcamento.getArremate());
    	   	   jComboBox4.setSelectedItem(itemOrcamento.getArremateInferior());


           }
           
       
       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel2)
               .addGap(18, 18, 18)
               .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel5)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2)
                   .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel3)
                   .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel5)
                   .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );


       jButton3.setText("ALTERAR");
       jButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton3ActionPerformed(evt);
           }
       });

       jButton2.setText("CANCELAR");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contramarco"));

       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jRadioButton1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jRadioButton2)
               .addGap(18, 18, 18)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                   .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGap(18, 18, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jComboBox3, 0, 120, Short.MAX_VALUE))
               .addGap(18, 18, 18))
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel4)
                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jRadioButton1)
                   .addComponent(jRadioButton2)
                   .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Arremate"));

       javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
       jPanel4.setLayout(jPanel4Layout);
       jPanel4Layout.setHorizontalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jRadioButton3)
               .addGap(18, 18, 18)
               .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel4Layout.createSequentialGroup()
                       .addGap(20, 20, 20)
                       .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel4Layout.createSequentialGroup()
                       .addGap(18, 18, 18)
                       .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(16, 16, 16)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(18, Short.MAX_VALUE))
       );
       jPanel4Layout.setVerticalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel7)
                   .addComponent(jLabel8))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jRadioButton3)
                   .addComponent(jRadioButton4)
                   .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(34, 34, 34)
               .addComponent(jButton3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton2)
               .addGap(35, 35, 35))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(labelCabecalho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(0, 0, 0)
               .addComponent(jLabel1)
               .addGap(18, 18, 18)
               .addComponent(labelCabecalho)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel11)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton3)
                   .addComponent(jButton2))
               .addContainerGap())
       );

       pack();
       
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

   }// </editor-fold>    
  
   
   private void initComponents(Orcamento orcamento,Produto produto) {
	   
	   orcamentoAberto = orcamento;
	   produtoAberto = produto;
	   
	   setTitle("Sistema para cálculo de esquadrias -> Orçamentos -> Itens orçamento -> Incluir produto");

       buttonGroup1 = new javax.swing.ButtonGroup();
       buttonGroup2 = new javax.swing.ButtonGroup();
       jPanel1 = new javax.swing.JPanel();
       jPanel2 = new javax.swing.JPanel();
       jPanel4 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       jLabel5 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel7 = new javax.swing.JLabel();
       jLabel8 = new javax.swing.JLabel();
       jLabel11 = new javax.swing.JLabel();
       labelCabecalho = new javax.swing.JLabel();
       txtAltura = new javax.swing.JTextField();
       txtLargura = new javax.swing.JTextField();
       txtQuantidade = new javax.swing.JTextField();
       jButton1 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jComboBox1 = new javax.swing.JComboBox<>();
       jComboBox2 = new javax.swing.JComboBox<>();
       jComboBox3 = new javax.swing.JComboBox<>();
       jComboBox4 = new javax.swing.JComboBox<>();
       jRadioButton1 = new javax.swing.JRadioButton();
       jRadioButton2 = new javax.swing.JRadioButton();
       jRadioButton3 = new javax.swing.JRadioButton();
       jRadioButton4 = new javax.swing.JRadioButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));

       jLabel2.setText("*Altura (mm):");

       jLabel3.setText("*Largura (mm):");

       jLabel5.setText("*Quantidade:");
       
       jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel4.setText("Laterais + Superior");
       
       jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel6.setText("Inferior");
       
       jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel7.setText("Laterais + Superior");

       jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel8.setText("Inferior");
       
       jLabel11.setText("Os campos com * são obrigatórios.");
       
       labelCabecalho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
       labelCabecalho.setText("Incluindo produto nº "+produto.getIdProduto()+" no orçamento nº "+orcamento.getIdOrcamento()+".");
               
       buttonGroup1.add(jRadioButton1);
       jRadioButton1.setText("Sem contramarco");
       jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton1ActionPerformed(evt);
           }
       });
       
       buttonGroup1.add(jRadioButton2);
       jRadioButton2.setText("Com contramarco");
       jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton2ActionPerformed(evt);
           }
       });
       
       buttonGroup2.add(jRadioButton3);
       jRadioButton3.setText("Sem arremate");
       jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton3ActionPerformed(evt);
           }
       });

       buttonGroup2.add(jRadioButton4);
       jRadioButton4.setText("Com arremate");
       jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jRadioButton4ActionPerformed(evt);
           }
       });
       
       //Configurar os radiobuttons e combobox
       jRadioButton1.setSelected(true);
       jRadioButton3.setSelected(true);

       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
       jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));

       jComboBox1.setEnabled(false);
       jComboBox3.setEnabled(false);

       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
       jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));

       jComboBox2.setEnabled(false);
       jComboBox4.setEnabled(false);

       
       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel2)
               .addGap(18, 18, 18)
               .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel5)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2)
                   .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel3)
                   .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel5)
                   .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );


       jButton1.setText("INCLUIR");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       jButton2.setText("CANCELAR");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contramarco"));

       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jRadioButton1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jRadioButton2)
               .addGap(18, 18, 18)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                   .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGap(18, 18, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jComboBox3, 0, 120, Short.MAX_VALUE))
               .addGap(18, 18, 18))
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel4)
                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jRadioButton1)
                   .addComponent(jRadioButton2)
                   .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       
       jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Arremate"));

       javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
       jPanel4.setLayout(jPanel4Layout);
       jPanel4Layout.setHorizontalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jRadioButton3)
               .addGap(18, 18, 18)
               .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel4Layout.createSequentialGroup()
                       .addGap(20, 20, 20)
                       .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel4Layout.createSequentialGroup()
                       .addGap(18, 18, 18)
                       .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(16, 16, 16)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(18, Short.MAX_VALUE))
       );
       jPanel4Layout.setVerticalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel7)
                   .addComponent(jLabel8))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jRadioButton3)
                   .addComponent(jRadioButton4)
                   .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(34, 34, 34)
               .addComponent(jButton1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton2)
               .addGap(35, 35, 35))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(labelCabecalho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(0, 0, 0)
               .addComponent(jLabel1)
               .addGap(18, 18, 18)
               .addComponent(labelCabecalho)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel11)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton1)
                   .addComponent(jButton2))
               .addContainerGap())
       );

       pack();
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
   	   this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

   }// </editor-fold>      
    
   
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	   
	 	
	  if(!jComboBox1.getSelectedItem().toString().contains("Selecione um item...") &&
			  !jComboBox2.getSelectedItem().toString().contains("Selecione um item...") &&
			  !jComboBox3.getSelectedItem().toString().contains("Selecione um item...") &&
			  !jComboBox4.getSelectedItem().toString().contains("Selecione um item...")) {
	  
	   try {
	    	ItemOrcamentoDAO iodao = new ItemOrcamentoDAO();
	    	ItemOrcamento io = new ItemOrcamento();

	    	io.setIdOrcamento(orcamentoAberto.getIdOrcamento());
	    	io.setIdProduto(produtoAberto.getIdProduto());
	    	io.setArremate(jComboBox2.getSelectedItem().toString());
	    	io.setArremateInferior(jComboBox4.getSelectedItem().toString());
	    	io.setContramarco(jComboBox1.getSelectedItem().toString());
	    	io.setContramarcoInferior(jComboBox3.getSelectedItem().toString());
	    	io.setLarguraMm(Integer.parseInt(txtLargura.getText()));
	    	io.setAlturaMm(Integer.parseInt(txtAltura.getText()));
	    	io.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
	    	
	    	iodao.criarItemOrcamento(io);
	    	
	    	this.dispose();
	    	new TelaItensOrcamento(orcamentoAberto).setVisible(true);;
	    	
	    	} catch (Exception e) { 
	    		JOptionPane.showMessageDialog(null, "Certifique-se que os três campos estão preenchidos "
	    			+ "com números!"); 
	    	}
	   
	  } else {
		  
		  JOptionPane.showMessageDialog(null, "selecione um item para o contramarco e arremate ou escolha a opção \"Sem arremate e/ou contramarco\"!");
		  
	  }
	    	
   }                                             

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	   
	   if(idItemOrcamento != -1) {
	   OrcamentoDAO oDAO =  new OrcamentoDAO();
	   ItemOrcamento io = itemOrcamentoDAO.lerObjItemOrcamento(idItemOrcamento);
	   Orcamento o = oDAO.lerObjOrcamento(io.getIdOrcamento());
	   this.dispose();
   	   new TelaItensOrcamento(o).setVisible(true);;
	   } else {
		   this.dispose();
		   new TelaItensOrcamento(orcamentoAberto).setVisible(true);
	   }
   }                                        

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	
	   if(!jComboBox1.getSelectedItem().toString().contains("Selecione um item...") &&
		  !jComboBox2.getSelectedItem().toString().contains("Selecione um item...") &&
		  !jComboBox3.getSelectedItem().toString().contains("Selecione um item...") &&
		  !jComboBox4.getSelectedItem().toString().contains("Selecione um item...")) {
	   try {
    		
        	ItemOrcamento io = itemOrcamentoDAO.lerObjItemOrcamento(idItemOrcamento);
        		
        	OrcamentoDAO oDAO = new OrcamentoDAO();
        	Orcamento o = oDAO.lerObjOrcamento(io.getIdOrcamento());
        	
        	io.setAlturaMm(Integer.parseInt(txtAltura.getText()));
        	io.setLarguraMm(Integer.parseInt(txtLargura.getText()));
        	io.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        	
        	io.setArremate(jComboBox2.getSelectedItem().toString());
        	io.setArremateInferior(jComboBox4.getSelectedItem().toString());
        	io.setContramarco(jComboBox1.getSelectedItem().toString());
	    	io.setContramarcoInferior(jComboBox3.getSelectedItem().toString());

        	itemOrcamentoDAO.update(io);
        	
        	this.dispose();
        	new TelaItensOrcamento(o).setVisible(true);;
        	
        	} catch (Exception e) { JOptionPane.showMessageDialog(null, "Certifique-se que os tres campos estão preenchidos "
        			+ "com números!"); }
	   } else {JOptionPane.showMessageDialog(null, "selecione um item para o contramarco e arremate ou escolha a opção \"Sem arremate e/ou contramarco\"!");}
	   
    }                                                                                    

   private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
	   
	   if(jRadioButton1.isSelected()) {
		   
		   jComboBox1.setEnabled(false);
		   jComboBox3.setEnabled(false);

  
           jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
           jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));

           
           jComboBox1.setSelectedItem("Não");
           jComboBox3.setSelectedItem("Não");

           
	   }  
   }     
   
   private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	  
	   if(jRadioButton2.isSelected()) {
		   
		   jComboBox1.setEnabled(true);
		   jComboBox3.setEnabled(true);

 
		   jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxContramarco()));
		   jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxContramarco()));

		   if (idItemOrcamento!=-1) {
			   
			   jComboBox1.setSelectedItem(itemOrcamentoDAO.lerObjItemOrcamento(idItemOrcamento).getContramarco());
			   jComboBox3.setSelectedItem(itemOrcamentoDAO.lerObjItemOrcamento(idItemOrcamento).getContramarcoInferior());

		   } else {
			   jComboBox1.setSelectedItem("Selecione um item...");
			   jComboBox3.setSelectedItem("Selecione um item...");

			   
		   }
	   }
	   
   }                                       

   private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	   
	   if(jRadioButton3.isSelected()) {
		   
		   jComboBox2.setEnabled(false);
		   jComboBox4.setEnabled(false);
  
           jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));
           jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Não"}));

           jComboBox2.setSelectedItem("Não");
           jComboBox4.setSelectedItem("Não");

	   }  
	   
   }                                             

   private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                              

	   if(jRadioButton4.isSelected()) {
		   
		   jComboBox2.setEnabled(true);
		   jComboBox4.setEnabled(true);

		   jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxArremate()));
		   jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(itemOrcamentoDAO.carregarComboxArremate()));
  
		   if (idItemOrcamento!=-1) {
			   jComboBox2.setSelectedItem(itemOrcamentoDAO.lerObjItemOrcamento(idItemOrcamento).getArremate());
			   jComboBox4.setSelectedItem(itemOrcamentoDAO.lerObjItemOrcamento(idItemOrcamento).getArremateInferior());

		   } else {
			   jComboBox2.setSelectedItem("Selecione um item...");
			   jComboBox4.setSelectedItem("Selecione um item...");

		   }
	   }
	   
   }                                             
   
   /**
    * @param args the command line arguments
    */
//   public static void main(String args[]) {
//       /* Set the Nimbus look and feel */
//       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//        */
//       try {
//           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//               if ("Nimbus".equals(info.getName())) {
//                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                   break;
//               }
//           }
//       } catch (ClassNotFoundException ex) {
//           java.util.logging.Logger.getLogger(JTableIncluirAlterarItemOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (InstantiationException ex) {
//           java.util.logging.Logger.getLogger(JTableIncluirAlterarItemOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (IllegalAccessException ex) {
//           java.util.logging.Logger.getLogger(JTableIncluirAlterarItemOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//           java.util.logging.Logger.getLogger(JTableIncluirAlterarItemOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       }
//       //</editor-fold>
//       //</editor-fold>
//       //</editor-fold>
//       //</editor-fold>
//
//       /* Create and display the form */
//       java.awt.EventQueue.invokeLater(new Runnable() {
//           public void run() {
//               new JTableIncluirAlterarItemOrcamento().setVisible(true);
//           }
//       });
//   }

   // Variables declaration - do not modify                     
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.ButtonGroup buttonGroup2;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JComboBox<String> jComboBox1;
   private javax.swing.JComboBox<String> jComboBox2;
   private javax.swing.JComboBox<String> jComboBox3;
   private javax.swing.JComboBox<String> jComboBox4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JRadioButton jRadioButton1;
   private javax.swing.JRadioButton jRadioButton2;
   private javax.swing.JRadioButton jRadioButton3;
   private javax.swing.JRadioButton jRadioButton4;
   private javax.swing.JLabel labelCabecalho;
   private javax.swing.JTextField txtAltura;
   private javax.swing.JTextField txtLargura;
   private javax.swing.JTextField txtQuantidade;
   // End of variables declaration                   
}
